### ISSUE TITLE
c++ highlighting

### ISSUE THREAD

**Issue by carlosdcastillo** [asottile/babi#151]
The multi line comment highlighting in C++ looks like this:

![babi](https://user-images.githubusercontent.com/5503702/126257058-4cd45b3a-8059-4c06-bd2e-7683e24d6c2c.png)

everything else looks and feels silky smooth.

How would I go about fixing the highlighting of multi line comments in C++?

**Comment by asottile** [comment]
very strange!  it seems to work fine for C though (and as far as I know they use the same grammar)

**Comment by asottile** [comment]
this should be fixed now!  I am working around `fileTypes` precedence in `babi-grammars`

if you `pip install 'babi-grammars>=0.0.29'` it should have a fix for this!

**Comment by carlosdcastillo** [comment]
I updated to the latest babi (0.22) and the latest babi-grammars (0.0.29). The highlighting does look really good on C++ files.

It is, however, exhibiting a new issue after this update on C++ files. Attached is a C++ file (please rename to position.cpp) if you hit page down all the way past the end it gives:

[position.txt](https://github.com/asottile/babi/files/7148524/position.txt)

It also gives the same error if you hit down arrow (instead of page down).

```
Traceback (most recent call last):
  File "/home/carlos/virtualenvs/sw/bin/babi", line 8, in <module>
    sys.exit(main())
  File "/home/carlos/virtualenvs/sw/lib/python3.7/site-packages/babi/main.py", line 151, in main
    return c_main(stdscr, filenames, positions, stdin, perf)
  File "/home/carlos/virtualenvs/sw/lib/python3.7/site-packages/babi/main.py", line 56, in c_main
    res = _edit(screen, stdin)
  File "/home/carlos/virtualenvs/sw/lib/python3.7/site-packages/babi/main.py", line 28, in _edit
    screen.draw()
  File "/home/carlos/virtualenvs/sw/lib/python3.7/site-packages/babi/screen.py", line 260, in draw
    self.file.draw(self.stdscr, self.margin)
  File "/home/carlos/virtualenvs/sw/lib/python3.7/site-packages/babi/file.py", line 863, in draw
    file_hl.highlight_until(self.buf, self.buf.file_y + to_display)
  File "/home/carlos/virtualenvs/sw/lib/python3.7/site-packages/babi/hl/syntax.py", line 115, in highlight_until
    state, regions = self._hl(state, lines[i], i == 0)
  File "/home/carlos/virtualenvs/sw/lib/python3.7/site-packages/babi/hl/syntax.py", line 61, in _hl_uncached
    self._compiler, state, f'{line}\n', first_line=first_line,
  File "/home/carlos/virtualenvs/sw/lib/python3.7/site-packages/babi/highlight.py", line 781, in highlight_line
    compiler, state, line, pos, first_line, boundary,
  File "/home/carlos/virtualenvs/sw/lib/python3.7/site-packages/babi/highlight.py", line 483, in search
    return _do_regset(idx, match, self, compiler, state, pos)
  File "/home/carlos/virtualenvs/sw/lib/python3.7/site-packages/babi/highlight.py", line 361, in _do_regset
    target_rule = compiler.compile_rule(rule.u_rules[idx])
  File "/home/carlos/virtualenvs/sw/lib/python3.7/site-packages/babi/highlight.py", line 661, in compile_rule
    ret = self._c_rules[rule] = self._compile_rule(grammar, rule)
  File "/home/carlos/virtualenvs/sw/lib/python3.7/site-packages/babi/highlight.py", line 629, in _compile_rule
    regs, rules = self._patterns(grammar, rule.patterns)
  File "/home/carlos/virtualenvs/sw/lib/python3.7/site-packages/babi/highlight.py", line 594, in _patterns
    grammar, rule.repository, rule.include,
  File "/home/carlos/virtualenvs/sw/lib/python3.7/site-packages/babi/highlight.py", line 574, in _include
    return self._patterns(grammar, (repository[s[1:]],))
  File "/home/carlos/virtualenvs/sw/lib/python3.7/site-packages/babi/fdict.py", line 46, in __getitem__
    raise KeyError(key)
KeyError: 'c_conditional_context'
```

**Comment by asottile** [comment]
ooh that's a bug with the cpp grammar itself!  nice find!

**Comment by asottile** [comment]
created an issue for that here, I'll see if I can fix it 🤔 https://github.com/jeff-hykin/better-cpp-syntax/issues/567

**Comment by asottile** [comment]
alrighty -- try with babi-grammars>=0.0.30 ?  I've hacked around the bug I linked above

**Comment by carlosdcastillo** [comment]
I've upgraded to 0.0.30 and it is working nicely 🚀
