### ISSUE TITLE
AttributeError: module 'curses' has no attribute 'A_ITALIC'

### ISSUE THREAD

**Issue by AshIsbitt** [asottile/babi#160]
(Babi 0.0.22, Python3.9,  MacOS 11.5, zsh 5.8 (x86_64-apple-darwin20.0), app installed/updated via `pip3 install`) This crash only appears when opening a pre-existing document (as opposed to a new buffer) and only when entering any of the following keys: 

`# $ 0 9 8 7 6 5 4 3 2 1 ' ; " | ` ?`

Strangely, it appears that sometimes it'll let me enter a single symbol and crash on the second instance of the same symbol (It will do this on the | and - symbols, but only sometimes. Other times it'll crash on the first entry)

Full crash Traceback: 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/babi", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/babi/main.py", line 151, in main
    return c_main(stdscr, filenames, positions, stdin, perf)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/babi/main.py", line 56, in c_main
    res = _edit(screen, stdin)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/babi/main.py", line 28, in _edit
    screen.draw()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/babi/screen.py", line 260, in draw
    self.file.draw(self.stdscr, self.margin)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/babi/file.py", line 863, in draw
    file_hl.highlight_until(self.buf, self.buf.file_y + to_display)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/babi/hl/syntax.py", line 115, in highlight_until
    state, regions = self._hl(state, lines[i], i == 0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/babi/hl/syntax.py", line 74, in _hl_uncached
    attr = self.attr(style)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/babi/hl/syntax.py", line 50, in attr
    curses.A_ITALIC * style.i |
AttributeError: module 'curses' has no attribute 'A_ITALIC'
```

**Comment by asottile** [comment]
hmm I guess it is only sometimes present unlike what is suggested in the docs: https://github.com/python/cpython/blob/c78d5ca3806d02e26f9f3fa92ff567f0805eac4c/Modules/_cursesmodule.c#L4850-L4852

by the way -- watch this video and you'll be better at formatting markdown: https://youtu.be/1UodxuXj5Ao
