### ISSUE TITLE
Usage with pipx

### ISSUE THREAD

**Issue by iasonkrom** [asottile/babi#330]
I used to be able to install `babi` with `pipx install babi` and use it fine until recently when I started getting the following error:
```
Traceback (most recent call last):
  File "/Users/iason/.local/bin/babi", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/iason/.local/pipx/venvs/babi/lib/python3.12/site-packages/babi/main.py", line 176, in main
    return c_main(stdscr, file_infos, stdin, perf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iason/.local/pipx/venvs/babi/lib/python3.12/site-packages/babi/main.py", line 63, in c_main
    res = _edit(screen, stdin)
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/iason/.local/pipx/venvs/babi/lib/python3.12/site-packages/babi/main.py", line 32, in _edit
    key = screen.get_char()
          ^^^^^^^^^^^^^^^^^
  File "/Users/iason/.local/pipx/venvs/babi/lib/python3.12/site-packages/babi/screen.py", line 302, in get_char
    ret = self._get_char()
          ^^^^^^^^^^^^^^^^
  File "/Users/iason/.local/pipx/venvs/babi/lib/python3.12/site-packages/babi/screen.py", line 283, in _get_char
    wch = _get_wch_with_retry(self.stdscr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iason/.local/pipx/venvs/babi/lib/python3.12/site-packages/babi/screen.py", line 114, in _get_wch_with_retry
    return stdscr.get_wch()
           ^^^^^^^^^^^^^^
AttributeError: '_curses.window' object has no attribute 'get_wch'. Did you mean: 'getch'?
```
Is this expected and using babi with pipx shouldn't work for some reason? Am I missing something? Thanks in advance.

**Comment by asottile** [comment]
this is unrelated to pipx, your python is poorly compiled (probably pyenv if I had to guess)
